use ad;

LOAD DATA LOCAL INFILE 'ebaydata.csv' 
	INTO TABLE EbayData  
	FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'category.csv' 
	INTO TABLE Category 
	FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'bidder.csv' 
	INTO TABLE Bidder 
	FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'bidlocation.csv' 
	INTO TABLE BidLocation 
	FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'bidamount.csv' 
	INTO TABLE BidAmount 
	FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'bidtime.csv' 
	INTO TABLE BidTime 
	FIELDS TERMINATED BY '|*|';
	
LOAD DATA LOCAL INFILE 'location.csv' 
	INTO TABLE Location 
	FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'seller.csv'
	INTO TABLE Seller 
	FIELDS TERMINATED BY '|*|';